{
 "title": "NCP",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "disks", "label": "Select Disks to display", "query": { "query": "node_filesystem_size_bytes" } },
   { "name": "max_disk_size_terrabytes", "label": "Assumed Maximum Disk Size", "query": "-2147484000000" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nextcloud Availability",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 7, "x": 0, "y": 1 },
     "targets": [
      { "expr": "nextcloud_up", "legendFormat": "{{hostname}}" }
     ]
    },
    {
     "title": "Federated Nextcloud Data Exchange Total",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 5, "x": 7, "y": 1 },
     "targets": [
      {
       "expr": "nextcloud_shares_federated_total",
       "legendFormat": "{{direction}}"
      }
     ]
    },
    {
     "title": "NC Version",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "nextcloud_system_info" }
     ]
    },
    {
     "title": "PHP Max Upload File Size",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 14, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nextcloud_php_upload_max_size_bytes"
      }
     ]
    },
    {
     "title": "PHP Max Memory Size",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 17, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nextcloud_php_memory_limit_bytes"
      }
     ]
    },
    {
     "title": "Total File Count",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "nextcloud_files_total" }
     ]
    },
    {
     "title": "Free Space Remaining",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "-nextcloud_free_space_bytes" }
     ]
    },
    {
     "title": "Total Shared Links by Type",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 5, "x": 15, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "nextcloud_shares_total", "legendFormat": "{{type}}" }
     ]
    },
    {
     "title": "NC Apps Installed",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "nextcloud_apps_installed_total" }
     ]
    },
    {
     "title": "CPU Load",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (rate(node_cpu_seconds_total{mode=\"idle\"}[1m]) * 100)",
       "legendFormat": "CPU {{cpu}}"
      },
      {
       "expr": "100 - (avg (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Currently Active Users",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "nextcloud_active_users_total" }
     ]
    },
    {
     "title": "Database Size",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "nextcloud_database_size_bytes" }
     ]
    },
    {
     "title": "Auth Errors",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(nextcloud_auth_errors_total[1h])"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "binbps" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_transmit_bytes_total{device!~\"(br-|docker).*\"}[1m])",
       "legendFormat": "network egress"
      },
      {
       "expr": "rate(node_network_receive_bytes_total{device!~\"(br-|docker).*\"}[1m])",
       "legendFormat": "network ingress"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 15, "x": 9, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
       "legendFormat": "used"
      },
      { "expr": "node_memory_MemTotal_bytes", "legendFormat": "max" }
     ]
    },
    {
     "title": "Disk IO by Disk",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "rate(node_disk_read_bytes_total{device!~\".*(zram|boot|dm-|mtdblock).*\"}[1m])",
       "legendFormat": "{{ device }} read"
      },
      {
       "expr": "rate(node_disk_written_bytes_total{device!~\".*(zram|boot|dm-|mtdblock).*\"}[1m])",
       "legendFormat": "{{ device }} write"
      },
      {
       "expr": "- rate(node_disk_io_time_seconds_total{device!~\".*(zram|boot|dm-|mtdblock).*\"}[1m])",
       "legendFormat": "{{ device }} load"
      },
      {
       "expr": "- rate(node_disk_written_bytes_total{device!~\".*(zram|boot|dm-|mtdblock).*\"}[1m])",
       "legendFormat": "{{ device }} write ghost"
      },
      {
       "expr": "rate(node_disk_read_bytes_total{device!~\".*(zram|boot|dm-|mtdblock).*\"}[1m])",
       "legendFormat": "{{ device }} read ghost"
      }
     ]
    },
    {
     "title": "Disk IO",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 21 },
     "yaxes": [
      { "format": "binbps" }
     ],
     "targets": [
      {
       "expr": "sum by (hostname) (rate(node_disk_read_bytes_total[1m]))",
       "legendFormat": "disk read"
      },
      {
       "expr": "sum by (hostname) (rate(node_disk_written_bytes_total[1m]))",
       "legendFormat": "disk write"
      }
     ]
    }
   ]
  },
  {
   "title": "Disks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Space",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "repeat": "disks",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{device=\"/dev/${disks}\"} - node_filesystem_avail_bytes{device=\"/dev/${disks}\"}",
       "legendFormat": "{{device}} [used]"
      },
      {
       "expr": "node_filesystem_avail_bytes{device=\"/dev/${disks}\"}",
       "legendFormat": "{{ device }} [free]"
      },
      {
       "expr": "node_filesystem_size_bytes{device=\"/dev/${disks}\"}",
       "legendFormat": "{{ device }} [total]"
      }
     ]
    },
    {
     "title": "IO/Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "repeat": "disks",
     "targets": [
      {
       "expr": "rate(node_disk_read_bytes_total{device=~\"${disks}\"}[1m])",
       "legendFormat": "{{ device }} read"
      },
      {
       "expr": "rate(node_disk_written_bytes_total{device=~\"${disks}\"}[1m])",
       "legendFormat": "{{ device }} write"
      },
      {
       "expr": "- rate(node_disk_io_time_seconds_total{device=~\"${disks}\"}[1m])",
       "legendFormat": "{{ device }} load"
      },
      {
       "expr": "- rate(node_disk_written_bytes_total{device=~\"${disks}\"}[1m])",
       "legendFormat": "{{ device }} write ghost"
      },
      {
       "expr": "rate(node_disk_read_bytes_total{device=~\"${disks}\"}[1m])",
       "legendFormat": "{{ device }} read ghost"
      }
     ]
    }
   ]
  }
 ]
}